version: "3"
services:
    postgress:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api
    api:
        depends_on: 
            - postgres
        image: vidhyajeyakumar7708/simple_blog_api
        build: .
        ports:
            - "3000:3000"
        environment: 
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api        