-- Create the table with partitions and Buckets
CREATE TABLE zipcodes
(RecordNumber int, Country string, City string, Zipcode int)
PARTITIONED BY (state string)
CLUSTERED BY (Zipcode) INTO 3 BUCKETS
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';

-- LOAD zipcodes.csv into the table
LOAD DATA LOCAL INPATH '/root/zipcodes.csv' INTO TABLE zipcodes;

-- View data in partition
SELECT * FROM zipcodes WHERE state='PR';
SELECT * FROM zipcodes WHERE state='PR' AND Zipcode=709;
